---
ID: "39254b29-fb31-4a4d-bb07-206177df8db1"
Parent: "915789cc-9dbe-420d-84c5-e4ee633fe4f4"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: /sitecore/content/Sugcon/SugconIndiaSxa/Settings/Shared Sites Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230518T045059Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\1ISa5gYrpM
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\1ISa5gYrpM
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "71873873-1c1f-4750-aa1f-ceee439cae4a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\1ISa5gYrpM
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230518T045059Z
