name: CI-CD - SUGCON ANZ
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_SUGCON_ANZ.yml
      - .github/workflows/build_NextJs.yml
      - .github/workflows/deploy_vercel.yml
      - 'src/Project/Sugcon/SugconAnzSxa/**'
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_SUGCON_ANZ.yml
      - .github/workflows/build_NextJs.yml
      - .github/workflows/deploy_vercel.yml
      - 'src/Project/Sugcon/SugconAnzSxa/**'

jobs:

  build-staging-anz-site:
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/build_NextJs.yml
    with:
      workingDirectory: ./src/Project/Sugcon/SugconAnzSxa
    secrets:
      JS_BUILD_ENDPOINT: ${{ secrets.JS_BUILD_ENDPOINT }}
      JS_BUILD_SECRET: ${{ secrets.STAGING_XM_CLOUD_EDGE_TOKEN }}

  build-production-anz-site:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build_NextJs.yml
    with:
      workingDirectory: ./src/Project/Sugcon/SugconAnzSxa
    secrets:
      JS_BUILD_ENDPOINT: ${{ secrets.JS_BUILD_ENDPOINT }}
      JS_BUILD_SECRET: ${{ secrets.PROD_XM_CLOUD_EDGE_TOKEN }}

  deploy-staging-anz-site:
    uses: ./.github/workflows/deploy_vercel.yml
    needs: [build-staging-anz-site, build-production-anz-site]
    if: always() && 
        needs.build-staging-anz-site.result != 'failure' &&
        needs.build-staging-anz-site.result != 'cancelled' && 
        needs.build-production-anz-site.result != 'failure' &&
        needs.build-production-anz-site.result != 'cancelled'
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SUGCON_ANZ_PROJECT_ID }}
