name: XM Cloud
on: 
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - '.github/workflows/CI-CD_MVP.yml' #IGNORE CHANGES TO GITHUB ACTIONS
    - '.github/workflows/CI-CD_SUGCON_ANZ.yml' #IGNORE CHANGES TO GITHUB ACTIONS
    - '.github/workflows/CI-CD_SUGCON_EU.yml' #IGNORE CHANGES TO GITHUB ACTIONS
    - '.github/workflows/deploy_azureWebapp.yml' #IGNORE CHANGES TO GITHUB ACTIONS
    - '.github/workflows/build_NextJs.yml' #IGNORE CHANGES TO GITHUB ACTIONS
    - 'src/Project/Sugcon/SugconAnzSxa/**' #IGNORE CHANGES TO Next.js head
    - 'src/Project/Sugcon/SugconEuSxa/**' #IGNORE CHANGES TO Next.js head
    - 'src/**/rendering/**' #IGNORE CHANGE TO MVP HEAD AND RELATED PROJECTS
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - '.github/workflows/CI-CD_MVP.yml' #IGNORE CHANGES TO GITHUB ACTIONS
    - '.github/workflows/CI-CD_SUGCON_ANZ.yml' #IGNORE CHANGES TO GITHUB ACTIONS
    - '.github/workflows/CI-CD_SUGCON_EU.yml' #IGNORE CHANGES TO GITHUB ACTIONS
    - '.github/workflows/deploy_azureWebapp.yml' #IGNORE CHANGES TO GITHUB ACTIONS
    - '.github/workflows/build_NextJs.yml' #IGNORE CHANGES TO GITHUB ACTIONS
    - 'src/Project/Sugcon/SugconAnzSxa/**' #IGNORE CHANGES TO Next.js head
    - 'src/Project/Sugcon/SugconEuSxa/**' #IGNORE CHANGES TO Next.js head
    - 'src/**/rendering/**' #IGNORE CHANGE TO MVP HEAD AND RELATED PROJECTS

jobs:

  build-dotnet:
    uses: ./.github/workflows/build_DotNet.yml
    with:
      buildConfiguration: Release

  deploy-staging:
    uses: ./.github/workflows/deploy_xmCloud.yml
    needs: build-dotnet 
    with:
      environmentName: Staging
    secrets:
      XM_CLOUD_CLIENT_ID: ${{ secrets.XM_CLOUD_CLIENT_ID }}
      XM_CLOUD_CLIENT_SECRET: ${{ secrets.XM_CLOUD_CLIENT_SECRET }}
      XM_CLOUD_ENVIRONMENT_ID: ${{ secrets.STAGING_XM_CLOUD_ENVIRONMENT_ID }}

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: deploy-staging 
    uses: ./.github/workflows/deploy_xmCloud.yml
    with:
      environmentName: Production
    secrets:
      XM_CLOUD_CLIENT_ID: ${{ secrets.XM_CLOUD_CLIENT_ID }}
      XM_CLOUD_CLIENT_SECRET: ${{ secrets.XM_CLOUD_CLIENT_SECRET }}
      XM_CLOUD_ENVIRONMENT_ID: ${{ secrets.PRODUCTION_XM_CLOUD_ENVIRONMENT_ID }}