name: SUGCON EU
on: 
  push:
    #branches: [ main ]
    paths:
      - .github/workflows/CI-CD_SUGCON_EU.yml
      - 'src/Project/Sugcon/SugconEuSxa/**'
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_SUGCON_EU.yml
      - 'src/Project/Sugcon/SugconEuSxa/**'

jobs:

  build-eu-site:
    uses: ./.github/workflows/build_NextJs.yml
    with:
      workingDirectory: ./src/Project/Sugcon/SugconEuSxa
    secrets:
      JS_BUILD_ENDPOINT: ${{ secrets.JS_BUILD_ENDPOINT }}
      JS_BUILD_SECRET: ${{ secrets.JS_BUILD_SECRET }}

  deploy-eu-site:
    uses: ./.github/workflows/deploy_vercel.yml
    needs: build-eu-site 
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SUGCON_EU_PROJECT_ID }}

  # deploy:
  #   name: Deploy the SUGCON EU rendering host to Vercel
  #   needs: build-eu-site
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: lts/*
  #     - uses: amondnet/vercel-action@v20
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         vercel-args: ${{ fromJSON('["--prod", ""]')[github.ref != 'refs/heads/main'] }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} 
  #         vercel-project-id: ${{ secrets.VERCEL_SUGCON_EU_PROJECT_ID}} 
  #         scope: ${{ secrets.VERCEL_ORG_ID}}
  #         working-directory: ./