name: CI-CD - SUGCON ANZ
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_SUGCON_ANZ.yml
      - .github/workflows/build_NextJs.yml
      - .github/workflows/deploy_vercel.yml
      - 'src/Project/Sugcon/SugconAnzSxa/**'
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_SUGCON_ANZ.yml
      - .github/workflows/build_NextJs.yml
      - .github/workflows/deploy_vercel.yml
      - 'src/Project/Sugcon/SugconAnzSxa/**'

jobs:

  build-anz-site:
    uses: ./.github/workflows/build_NextJs.yml
    with:
      workingDirectory: ./src/Project/Sugcon/SugconAnzSxa
    secrets:
      JS_BUILD_ENDPOINT: ${{ secrets.JS_BUILD_ENDPOINT }}
      JS_BUILD_SECRET: ${{ fromJSON('["secrets.PROD_XM_CLOUD_EDGE_TOKEN", "secrets.STAGING_XM_CLOUD_EDGE_TOKEN"]')[github.ref != 'refs/heads/main'] }}

  deploy-anz-site:
    uses: ./.github/workflows/deploy_vercel.yml
    needs: build-anz-site 
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SUGCON_ANZ_PROJECT_ID }}