name: Build and Release CM + MVP Site
on: 
  push:
    #branches: [ main ]
    paths-ignore:
    - 'README.md'
    #- '.github/workflows/**' #IGNORE CHANGES TO GITHUB ACTIONS
    - 'src/Project/Sugcon/SugconAnzSxa/**' #IGNORE CHANGES TO Next.js head
    - 'src/Project/Sugcon/SugconEuSxa/**' #IGNORE CHANGES TO Next.js head
    - 'src/**/rendering/**' #IGNORE CHANGE TO MVP HEAD AND RELATED PROJECTS
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - '.github/workflows/**' #IGNORE CHANGES TO GITHUB ACTIONS
    - 'src/Project/Sugcon/SugconAnzSxa/**' #IGNORE CHANGES TO Next.js head
    - 'src/Project/Sugcon/SugconEuSxa/**' #IGNORE CHANGES TO Next.js head
    - 'src/**/rendering/**' #IGNORE CHANGE TO MVP HEAD AND RELATED PROJECTS

jobs:

  build-dotnet:
    name: Build the .NET Solution
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6
    - name: Restore NuGet packages
      run: nuget restore src\XmCloudIntroduction.sln
    - name: Build
      run: msbuild src\XmCloudIntroduction.sln /p:Configuration=Release

  deploy-staging:
    name: Deploy the XM Cloud Staging Site
    #if: github.ref == 'refs/heads/main'
    needs: [build-dotnet]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' 
    - run: dotnet tool restore
    - run: dotnet sitecore --help
    - name: Authenticate CLI with XM Cloud
      run: dotnet sitecore cloud login --client-credentials --client-id ${{ secrets.PROD_CLIENT_ID }} --client-secret ${{ secrets.PROD_CLIENT_SECRET }}
    - name: Deploy the CM assets to XM Cloud
      run: dotnet sitecore cloud deployment create --environment-id ${{ secrets.STAGING_XM_CLOUD_ENVIRONMENT_ID }} --upload 
    - name: Authenticate default environment with CLI
      run: dotnet sitecore login --ref xmcloud --client-credentials true --client-id ${{ secrets.PROD_CLIENT_ID }} --client-secret ${{ secrets.PROD_CLIENT_SECRET }} --cm ${{ secrets.STAGING_XM_CLOUD_CM_URL }} --allow-write true
    - name: Publish content changes
      run: dotnet sitecore publish --pt Edge
   
  deploy-production:
    name: Deploy the XM Cloud Production Site
    #if: github.ref == 'refs/heads/main'
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' 
    - run: dotnet tool restore
    - run: dotnet sitecore --help
    - name: Authenticate CLI with XM Cloud
      run: dotnet sitecore cloud login --client-credentials --client-id ${{ secrets.PROD_CLIENT_ID }} --client-secret ${{ secrets.PROD_CLIENT_SECRET }}
    - name: Deploy the CM assets to XM Cloud
      run: dotnet sitecore cloud deployment create --environment-id ${{ secrets.PROD_ENVIRONMENT_ID }} --upload 
    - name: Authenticate default environment with CLI
      run: dotnet sitecore login --ref xmcloud --client-credentials true --client-id ${{ secrets.PROD_CLIENT_ID }} --client-secret ${{ secrets.PROD_CLIENT_SECRET }} --cm ${{ secrets.PROD_CM_URL }} --allow-write true
    - name: Publish content changes
      run: dotnet sitecore publish --pt Edge 