name: MVP Site
on: 
  push:
    branches: [ main ]
    paths:
      - 'src/**/rendering/**'
      - .github/workflows/deploy_MVP.yml
      - .github/workflows/build_DotNet.yml
      - .github/workflows/azure_deployWebapp.yml
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**/rendering/**'
      - .github/workflows/deploy_MVP.yml
      - .github/workflows/build_DotNet.yml
      - .github/workflows/azure_deployWebapp.yml

jobs:

  build-dotnet:
    uses: ./.github/workflows/build_DotNet.yml
    with:
      buildConfiguration: Release

  deploy-mvp-staging:
    uses: ./.github/workflows/azure_deployWebapp.yml
    needs: build-dotnet 
    with:
      buildConfiguration: Debug
      projectLocation: src/Project/MvpSite/rendering
      assetName: Mvp-Staging
    secrets:
      publishingProfile: ${{ secrets.STAGING_MVP_WEBAPP_PUBLISHING_PROFILE }}
      
  deploy-mvp-prod:
    if: github.ref == 'refs/heads/main'
    needs: deploy-mvp-staging 
    uses: ./.github/workflows/azure_deployWebapp.yml
    with:
      buildConfiguration: Release
      projectLocation: src/Project/MvpSite/rendering
      assetName: Mvp-prod
    secrets:
      publishingProfile: ${{ secrets.PROD_MVP_WEBAPP_PUBLISHING_PROFILE }}